(defun module-go--install-packages ()
  (pkgmgr-install '(go-mode auto-complete go-autocomplete)))

(defun go-path () (getenv "GOPATH"))

(defun add-go-path-bin-to-exec-path ()
  (add-to-list 'exec-path (concat (go-path) "/bin")))
(defun module-go-hook ()
  (require 'auto-complete)
  (require 'go-autocomplete)
  (auto-complete-mod)
  (add-hook 'before-save-hook 'gofmt-before-save)
  (local-set-key (kbd "M-.") 'godef-jump)
  (local-set-key (kbd "M-*") 'pop-tag-mark)
  )
(defun module-go-setup ()
  (interactive)
  (module-go--install-packages)
  (add-go-path-bin-to-exec-path)
  (add-hook 'go-mode-hook 'module-go-hook)
  )
(provide 'go)
