#!/bin/bash
mkdir -p ${HOME}/.negev/lib
cp -r ./lib/* ${HOME}/.negev/lib/
cp -r negev-config.el ${HOME}/.negev/
printf "#!/bin/bash\nemacs -q -l ${HOME}/.negev/negev-config.el &" > ./negev-bin
sudo mv ./negev-bin /usr/bin/negev
sudo chmod +x /usr/bin/negev
