(defun module-json--install-packages ()
  (pkgmgr-install '(json-mode)))
(defun module-json-setup ()
  (module-json--install-packages)
  (add-hook 'before-save-hook 'json-mode-beautify))
(provide 'modules/json)
